### PR TITLE
Add all benchmarks

### PR DESCRIPTION
**Pull request by HamasWaqar**
This branch, in a brief overview, adds all of the NoC-CGRA benchmarks into UGRAMM.

1. The benchmark_modification.py script was modified to include pragmas and remove any unnecessary attributes required by CGRA-ME
2. The constrant_duplication.py script was modified to include pragmas and include case insensitivity when searching for constants in the device model graph
3. Remove the application_graph_modification.py script as it was not required as it performs the same conversions as the  benchmark_modification.py script
4. Generated the kernels for Conv_nonBalance, FFT-Radix_5, FFT-Radix4, Stencil_Balance, and Stencil_nonBalanced

### CODE REVIEW

**Comment by HamasWaqar** [comment]
@ombhilare999, could you also approve this pull request too.

**Comment by ombhilare999** [comment]
Hi @HamasWaqar,

Let's try to merge the #20 first before coming to this #21 PR.

**Comment by HamasWaqar** [comment]
Merged #20, I am good to go with merging this branch @ombhilare999 ?

**Comment by ombhilare999** [comment]
Hi @HamasWaqar,

Everything looks good. Do you want to revert the `config.json` and `run_UGRAMM.sh` changes from this branch, cause it may hinder the recent updates that you have done in your older PR.

You can merge this afterwards, thanks.

**Comment by ombhilare999** [comment]
Hi @HamasWaqar,

Can we merge this PR as well?

**Pull request merged**
